#!/bin/bash

CWD=$(pwd)

# Takes an expected and actual Status Code
# Usage: resultCheck 200 $RETURNED_CODE
function resultCheck() {
  local EXPECTED=$1
  local ACTUAL=$2
  if [ "$EXPECTED" -ne "$ACTUAL" ]; then
    echo "ERROR expected $EXPECTED and received $ACTUAL"
    if [ "$ACTUAL" == "405" ]; then
      echo "ERROR check the FEDORA_PATH setting in the config file to ensure you're pointing to the repository correctly."
    fi

    exit 1
  fi
  echo "$EXPECTED == $ACTUAL (Pass)"
  return 0
}

# Takes an expected string and returned value
# Usage: resultCheckString "This is the title" $RETURNED_TITLE
function resultCheckString() {
  local EXPECTED=$1
  local ACTUAL=$2
  if [ "$EXPECTED" != "$ACTUAL" ]; then
    echo "ERROR expected $EXPECTED and received $ACTUAL"
    exit 1
  fi
  echo "$EXPECTED == $ACTUAL (Pass)"
  return 0
}

# Takes an expected Status Code and grabs the other from Headers.
# NOTE: Header variable must be wrapped in quotes when calling.
# Usage: resultCheckInHeaders 200 "$RETURNED_CODE"
function resultCheckInHeaders() {
  local EXPECTED=$1
  local HEADERS=$2
  local ACTUAL=$(echo "$HEADERS" | grep 'HTTP/1.1' | cut -d' ' -f2)
  if [ "$EXPECTED" -ne "$ACTUAL" ]; then
    echo "ERROR expected $EXPECTED and received $ACTUAL"
    if [ "$ACTUAL" == "405" ]; then
      echo "ERROR check the FEDORA_PATH setting in the config file to ensure you're pointing to the repository correctly."
    fi

    exit 1
  fi
  echo "$EXPECTED == $ACTUAL (Pass)"
  return 0
}

# Find the Location: header and return the value in the LOCATION variable.
# NOTE: Header variable must be wrapped in quotes when calling.
# Usage: getLocationFromHeaders "$HEADERS"
# Return: Location URL in the $LOCATION variable.
function getLocationFromHeaders() {
  local HEADERS=$1
  export LOCATION=$(echo "$HEADERS" | grep '^Location:' | cut -d' ' -f2 | tr -d '\r')
  if [ -z "$LOCATION" ]; then
    echo "Could not find the Location: header"
    return 1
  else
    return 0
  fi
}

# Check that the Content-Type header matches the expected value.
# NOTE: Header variable must be wrapped in quotes when calling.
# Usage: checkContentType "expected/content-type" "$HEADERS"
function checkContentType() {
  local EXPECTED="$1"
  local HEADERS=$2
  local ACTUAL=$(echo "$HEADERS" | grep '^Content-Type:' | cut -d' ' -f2 | tr -d '\r')
  if [ "$EXPECTED" == "$ACTUAL" ]; then
    echo "$EXPECTED == $ACTUAL (Pass)"
    return 0
  else
    echo "ERROR: expected Content-Type to be \"$EXPECTED\", but was \"$ACTUAL\""
    return 1
  fi
}

# Check the dc:title value of a resource.
# Usage: checkTitle "Expected Title" $URL
function checkTitle() {
  local EXPECTED="$1"
  local TRIPLES=$(curl $CUSTOM_CURL_OPTS -H "Accept: application/n-triples" -u"${AUTH_USER}:${AUTH_PASS}" "${2}")
  local ACTUAL=$(echo "$TRIPLES" | grep "<http://purl.org/dc/elements/1.1/title>" | cut -d\" -f2)
  if [ "$EXPECTED" == "$ACTUAL" ]; then
    echo "$EXPECTED == $ACTUAL (Pass)"
    return 0
  else
    echo "ERROR: expected dc:title to be \"$EXPECTED\", but was \"$ACTUAL\""
    return 1
  fi
}

# Searches the provided response for Link headers
# and matches against the provided expected.
# Usage: assertLinkHeader "<expected URI>;rel=\"title\"" "$HTTP_RES"
function assertLinkHeader() {
  local EXPECTED=$1
  local RESPONSE=$2
  for l in $(echo "$RESPONSE" | grep '^Link:' | sed -e 's/ /_/g' | cut -d'<' -f2 | tr -d '\r') ; do
    local newLink="<"$(echo "$l" | sed -e 's/_//g')
    if [ "${EXPECTED}" == "$newLink" ]; then
      echo "Link header $EXPECTED == $newLink (Pass)"
      return 0
    fi
  done
  echo "ERROR: Expected Link header $EXPECTED, did not find one."
  return 1
}

function countMementos() {
  local RESPONSE=$1
  local counts=0
  for l in $(echo "$RESPONSE" | sed -e 's/ /_/g' ) ; do
    local newLink=$(echo "$l" | sed -e 's/_//g')
    if [[ "$newLink" =~ 'rel="memento"' ]]; then
      counts=$(expr $counts + 1)
    fi
  done
  echo $counts
}
# Check if the parent object of the tests exists, delete if requested.
# Takes the parent object path
function checkForReTest() {
  local URL=$1
  local HTTP_RES=$(curl $CURL_OPTS -XPUT -u${AUTH_USER}:${AUTH_PASS} ${FEDORA_URL}${URL})
  if [ "$HTTP_RES" != "201" ]; then
    if [ "$HTTP_RES" == "000" ]; then
      echo "Attempted to run test but received odd results (HTTP status of $HTTP_RES). Is Fedora4 running?"
      exit 1
    else
      echo "This test has been run. You need to remove this object and all it's children before re-running the test."
      read -p "Remove the test objects and re-run? (y/N) " RERUN
      if [ "$RERUN" == "Y" ] || [ "$RERUN" == "y" ]; then
        if cleanUpPath "$URL"
        then
          local HTTP_RES=$(curl $CURL_OPTS -XPUT -u${AUTH_USER}:${AUTH_PASS} ${FEDORA_URL}${URL})
        else
          echo "Error removing $URL, you may need to remove it manually."
          exit 1
        fi
      else
        exit 1
      fi
    fi
  fi
  return 0
}

# Delete the object at path $URL including it's tombstone
function cleanUpPath() {
  local URL=$1
  echo "Deleting ${FEDORA_URL}${URL}"
  local HTTP_RES=$(curl $CURL_OPTS -u${AUTH_USER}:${AUTH_PASS} -XDELETE ${FEDORA_URL}${URL})
  if [ "$HTTP_RES" == "204" ] || [ "$HTTP_RES" == "410" ]; then
    local HTTP_RES=$(curl $CURL_OPTS -u${AUTH_USER}:${AUTH_PASS} -XDELETE ${FEDORA_URL}${URL}/fcr:tombstone)
    if [ "$HTTP_RES" == "204" ]; then
      return 0
    fi
  fi
  return 1
}

# Check to see if the test objects at $PARENT path should be deleted.
function cleanUpTests() {
  local PARENT=$1
  read -p "Remove any test objects created? (Y/n) " DELETE
  if [ "$DELETE" == "y" ] || [ "$DELETE" == 'y' ] || [ "$DELETE" == "" ]; then
    cleanUpPath "$PARENT"
  fi
}
